// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATEU_LekXjtp3DzkcSXNr9rJF84-NrH98',
    appId: '1:706637163086:web:5fb016d936b40e5fa8711f',
    messagingSenderId: '706637163086',
    projectId: 'stressometer-3da0a',
    authDomain: 'stressometer-3da0a.firebaseapp.com',
    storageBucket: 'stressometer-3da0a.firebasestorage.app',
    measurementId: 'G-GG6Z87EG2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBucV2DF_JqMLhX4KQ4NZJ0pniscWgnoxY',
    appId: '1:706637163086:android:0b282e795bb6bc19a8711f',
    messagingSenderId: '706637163086',
    projectId: 'stressometer-3da0a',
    storageBucket: 'stressometer-3da0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2c2QkRZ5_VAMDVq_aN014pdRrKqxz2c',
    appId: '1:706637163086:ios:0ae88661b61d6236a8711f',
    messagingSenderId: '706637163086',
    projectId: 'stressometer-3da0a',
    storageBucket: 'stressometer-3da0a.firebasestorage.app',
    iosBundleId: 'com.example.stressometer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2c2QkRZ5_VAMDVq_aN014pdRrKqxz2c',
    appId: '1:706637163086:ios:0ae88661b61d6236a8711f',
    messagingSenderId: '706637163086',
    projectId: 'stressometer-3da0a',
    storageBucket: 'stressometer-3da0a.firebasestorage.app',
    iosBundleId: 'com.example.stressometer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATEU_LekXjtp3DzkcSXNr9rJF84-NrH98',
    appId: '1:706637163086:web:673807353773a50fa8711f',
    messagingSenderId: '706637163086',
    projectId: 'stressometer-3da0a',
    authDomain: 'stressometer-3da0a.firebaseapp.com',
    storageBucket: 'stressometer-3da0a.firebasestorage.app',
    measurementId: 'G-0YD78XWMBF',
  );
}
